#!/usr/bin/env bash
# This loop displays 4 and bad luck from china on 4th loop iteration, 9 and bad k=luck fromm japan on the 9th loop iteration and 17 and then bad luck from italy onteh 17th loop iteration
i=1

while [ $i -le 20 ]
do
    echo "$i"
    case $i in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    i=$((i + 1))
done

